server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eightshoppingmail?useSSL-=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: wyh1234
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
  mvc:
    view:
      prefix: webpage/
      suffix: .html
mybatis:
  type-aliases-package: com.eight.bean
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
#    查看Sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      example:
        mapper : debug
